default: &default
  adapter: postgresql
  encoding: utf8
  min_messages: log
  pool: <%= ::AppConfig["max_web_threads"] %>
  reaping_frequency: <%= ::AppConfig["database_reaping_frequency"] %>
  timeout: <%= ::AppConfig["database_timeout"] %>
  url: <%= ::AppConfig["database_url"] %>

development:
  <<: *default
  database: rpgazebo_development

test:
  <<: *default
  database: rpgazebo_test

production:
  <<: *default
  database: rpgazebo_production
